url: https://www.fertig2020.fr
baseurl: 
simpleform-token: "https://getsimpleform.com/messages?form_api_token=c7eaecdb54c780ec7ea89fa7c4b62823"

# Site settings
title: "Steeve FERTIG : un engagement naturel"
email: steevefertig2020@gmail.com
description: "Le site de campagne de la liste Steeve FERTIG aux éléctions municipales 2020 à Ingwiller."
lang: fr-FR



# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap